### ISSUE TITLE
golangci-lint -> an integration with Sonar

### ISSUE THREAD

**Issue by SergiiOliinyk** [uartois/sonar-golang#74]
Would u consider to implement an integration golangci-lint with Sonar ? 
https://github.com/golangci/golangci-lint

**Comment by thibaultfalque** [comment]
Hello @SergiiOliinyk, 

I will check if it's possible. 

Thanks for your feedback.

**Comment by SergiiOliinyk** [comment]
@thibaultfalque thx!

**Comment by thibaultfalque** [comment]
Hello @SergiiOliinyk 

I tried to use `golangci-lint` with the plugin. Because it does not use exactly the same format many violations are not displayed, even though some are. 

I am going to update the plugin to consider the violations which are not recognized.

You can still execute the plugin (but violations will be missing). To do so, you will need to create the yaml file specified in the [documentation of golangci-lint](https://github.com/golangci/golangci-lint#config-file), and to edit it to comply with the plugin's expected input format, which must be `checkstyle`, as in the following:

```yaml

# [...]

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: checkstyle
```

To execute the analysis, you need to run: `golangci-lint run -c .golangci.yml > report.xml`
